# Nombre de la base de datos y ruta (se creará un archivo llamado deustodb.mv.db)
spring.datasource.url=jdbc:h2:file:./data/deustodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Esto permite que las tablas se creen solas si no existen
spring.jpa.hibernate.ddl-auto=create-drop
spring.show-sql=true

# Consola de H2 para que puedas ver los datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console