# Nombre de la base de datos y ruta (deustodb.mv.db)
spring.datasource.url=jdbc:h2:file:./data/deustodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Esto hace que las tablas se creen solas si no existen
spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true

# Consola de H2 para ver los datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console